GET http://127.0.0.1:3001/books HTTP/1.1
Content-Type: application/json

###

#Update a book
POST  http://127.0.0.1:3001/books HTTP/1.1
Content-Type: application/json

{
    "title": "Harry Potter"
}

###

PUT  http://127.0.0.1:3001/books/7 HTTP/1.1
Content-Type: application/json


{
    "title": "Harry Potter 25"
}

###

#Delete a book
DELETE  http://127.0.0.1:3001/books/2 HTTP/1.1
Content-Type: application/json


{
    "title": "Harry Potter "
}

